version: "3.9"
services:
  gpt:
    image: ghcr.io/mlsh0/tg-openai:latest
    container_name: gpt
    networks:
      - proxy
    labels:
      - "traefik.enable=false"
    env_file:
      - ./variables.env
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 3m

networks:
  proxy:
    external: true
